[versions]
checkerframework = "3.37.0"
netty = "4.1.101.Final"
jackson = "2.18.0"
adventure = "4.24.0"
junit = "5.9.2"

[libraries]
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
checker = { group = "org.checkerframework", name = "checker", version.ref = "checkerframework" }
adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-text-serializer-json = { group = "net.kyori", name = "adventure-text-serializer-json", version.ref = "adventure" }

fastutil-bom = { group = "org.cloudburstmc.fastutil", name = "bom", version = "8.5.15" }
fastutil-long-common = { group = "org.cloudburstmc.fastutil.commons", name = "long-common" }
fastutil-long-object-maps = { group = "org.cloudburstmc.fastutil.maps", name = "long-object-maps" }
fastutil-int-object-maps = { group = "org.cloudburstmc.fastutil.maps", name = "int-object-maps" }
fastutil-object-int-maps = { group = "org.cloudburstmc.fastutil.maps", name = "object-int-maps" }

netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-transport-raknet = { group = "org.cloudburstmc.netty", name = "netty-transport-raknet", version = "1.0.0.CR3-SNAPSHOT" }

jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version = "0.9.6" }
natives = { group = "com.nukkitx", name = "natives", version = "1.0.3" }
math = { group = "org.cloudburstmc.math", name = "immutable", version = "2.0-SNAPSHOT" }
nbt = { group = "org.cloudburstmc", name = "nbt", version = "3.0.3.Final" }
lmbda = { group = "org.lanternpowered", name = "lmbda", version = "2.0.0" }

snappy = { group = "io.airlift", name = "aircompressor", version = "0.27" }

junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }

[plugins]
checkerframework = { id = "org.checkerframework", version = "0.6.29" }
lombok = { id = "io.freefair.lombok", version = "6.6.3" }
